### PR TITLE
[Task#68013] Init project, add pull request template and CI

### PR DESCRIPTION
**Pull request by tungbd-0214**
## Related Tickets:
- [#68013](https://edu-redmine.sun-asterisk.vn/issues/68013)

## WHAT this PR does?
- Init project, add pull request template and CI.

## Notes Impacted Areas:
- N/A.

## Attachments:
Screen Shot 2023-09-12 at 01 35 47

### CODE REVIEW

**Review by dangvm-0369 — APPROVED** [review]
oke

**Review by Hungnd-0370 — APPROVED** [review]
oke

**Comment by tungbd-0214** [comment]
ready

**Comment by ghost** [comment]
description PR ko chính xác

**Review by ghost — COMMENTED** [review]
commented

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
merged

**Pull request merged**
