### PR TITLE
[Task#67796] Setup salon register UI for guest

### PR DESCRIPTION
**Pull request by tungbd-0214**
## Related Tickets:
- [#67796](https://edu-redmine.sun-asterisk.vn/issues/67796)

## WHAT this PR does?
- Setup salon register UI for guest

## Notes Impacted Areas:
- N/A.

## Attachments:
Screen Shot 2023-09-13 at 15 27 05

Screen Shot 2023-09-13 at 15 31 33

### CODE REVIEW

**Comment by tungbd-0214** [comment]
ready

**Review by Hungnd-0370 — APPROVED** [review]
oke

**Review by ghost — COMMENTED** [review]
public css js ignore...

**Comment by tungbd-0214** [comment]
ready

**Review by ghost — COMMENTED** [review]
merged

**Pull request merged**
